MODULE glut_fonts
  USE iso_c_binding ,ONLY: C_PTR
  IMPLICIT NONE
  TYPE(C_PTR), BIND(C), PROTECTED :: GLUT_STROKE_ROMAN, &
    GLUT_STROKE_MONO_ROMAN, GLUT_BITMAP_9_BY_15, GLUT_BITMAP_8_BY_13, &
    GLUT_BITMAP_TIMES_ROMAN_10, GLUT_BITMAP_TIMES_ROMAN_24,           &
    GLUT_BITMAP_HELVETICA_10, GLUT_BITMAP_HELVETICA_12,               &
    GLUT_BITMAP_HELVETICA_18
END MODULE glut_fonts